events {}

http {
    server {
        listen 80;

        location / {
            proxy_pass http://app:5000/public;
        }

        location /public {
            proxy_pass http://app:5000/public/;
        }

        location /public/ {
            proxy_pass http://app:5000/public/;
        }

        location /static {
            proxy_pass http://app:5000/static/;
        }

        location /static/ {
            proxy_pass http://app:5000/static/;
        }
    }
    server {
        listen 81;
        location / {
            proxy_pass http://app:5000/;
        }
    }
}